<a href="https://colab.research.google.com/github/eogks1235-byte/DEEP_Learning-feat.Jake-Oh/blob/main/ml22_llm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EXAONE 모델을 사용한 질문-답변 시스템

현재 Colab에 설치된 transformers 패키지의 버전은 5.0.0.

EXAONE 모델을 사용하기 위해서는 5.1.0 버전이 필요.

In [2]:
!pip install -U transformers==5.1.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 92.6 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0


Imports

In [3]:
import numpy as np
import scipy
import transformers

In [4]:
transformers.__version__

'5.1.0'

In [5]:
# 깃허브에 .ipynb 파일을 업로드할 때 다운로드 상태(진행바) 표시줄때문에 오류 발생
# -> 깃허브에 정상적으로 업로드되게 하기 위해서
transformers.utils.logging.disable_progress_bar()

# EXAONE-3.5 모델

In [6]:
# GPU변경

In [7]:
pipe=transformers.pipeline(
    task='text-generation',
    model='LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct',
    device=0, # GPU 사용
    trust_remote_code=True
)

A new version of the following files was downloaded from https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct:
- configuration_exaone.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct:
- modeling_exaone.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


In [8]:
# 메시지 템플릿: 'role'과 'content'를 키로 갖는 dict들을 아이템으로 갖는 리스트.
# role: 역할(system, user, assistant)
# content: 내용
messages=[
    {
        'role':'system',
        'content':'너는 쇼핑몰 Q&A에 올라온 질문에 답변하는 챗봇이야. \
        확정적인 답변을 하지 말고, 제품 담당자가 정확한 답변을 하기 위해 시간이 필요하다는 \
        간단하고 친절한 답변을 생성해줘.'
    },
    {
        'role':'user',
        'content':'이 다이어리에는 내년의 공휴일이 표기되어 있나요?'
    }

]

In [9]:
result= pipe(messages, max_new_tokens=200)

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


In [10]:
print(result)
# pipeline 호출 결과: 'generated_text' 키를 갖는 dict 1개를 저장하고 있는 리스트

[{'generated_text': [{'role': 'system', 'content': '너는 쇼핑몰 Q&A에 올라온 질문에 답변하는 챗봇이야.         확정적인 답변을 하지 말고, 제품 담당자가 정확한 답변을 하기 위해 시간이 필요하다는         간단하고 친절한 답변을 생성해줘.'}, {'role': 'user', 'content': '이 다이어리에는 내년의 공휴일이 표기되어 있나요?'}, {'role': 'assistant', 'content': '안녕하세요! 다이어리에 내년의 공휴일이 정확히 어떻게 포함되어 있는지 확인해 드리려면 제품 담당자님이 최신 정보를 바탕으로 확인이 필요합니다. 하지만 대부분의 고급 다이어리는 각 연도별로 공휴일을 포함하도록 제작되어 있으니, 내년 공휴일 정보도 포함되어 있을 가능성이 높습니다. 정확한 내용을 확인하려면 가까운 매장이나 고객 서비스에 연락하시는 게 가장 좋을 것 같아요. 도움이 되셨길 바라며, 빠른 답변 부탁드립니다! 😊'}]}]


In [11]:
len(result)

1

In [12]:
result[0] # 딕셔너리 값으로 리스트

{'generated_text': [{'role': 'system',
   'content': '너는 쇼핑몰 Q&A에 올라온 질문에 답변하는 챗봇이야.         확정적인 답변을 하지 말고, 제품 담당자가 정확한 답변을 하기 위해 시간이 필요하다는         간단하고 친절한 답변을 생성해줘.'},
  {'role': 'user', 'content': '이 다이어리에는 내년의 공휴일이 표기되어 있나요?'},
  {'role': 'assistant',
   'content': '안녕하세요! 다이어리에 내년의 공휴일이 정확히 어떻게 포함되어 있는지 확인해 드리려면 제품 담당자님이 최신 정보를 바탕으로 확인이 필요합니다. 하지만 대부분의 고급 다이어리는 각 연도별로 공휴일을 포함하도록 제작되어 있으니, 내년 공휴일 정보도 포함되어 있을 가능성이 높습니다. 정확한 내용을 확인하려면 가까운 매장이나 고객 서비스에 연락하시는 게 가장 좋을 것 같아요. 도움이 되셨길 바라며, 빠른 답변 부탁드립니다! 😊'}]}

In [13]:
result[0].keys()

dict_keys(['generated_text'])

result - `[ { 'generated_text': [...] } ]`

In [14]:
result[0]['generated_text']
# 'role'과 'content'를 키로 갖는 dict들의 list.
# 3개의 dict: 첫 2개는 입력값, 마지막 1개 AI가 생성한 답변

[{'role': 'system',
  'content': '너는 쇼핑몰 Q&A에 올라온 질문에 답변하는 챗봇이야.         확정적인 답변을 하지 말고, 제품 담당자가 정확한 답변을 하기 위해 시간이 필요하다는         간단하고 친절한 답변을 생성해줘.'},
 {'role': 'user', 'content': '이 다이어리에는 내년의 공휴일이 표기되어 있나요?'},
 {'role': 'assistant',
  'content': '안녕하세요! 다이어리에 내년의 공휴일이 정확히 어떻게 포함되어 있는지 확인해 드리려면 제품 담당자님이 최신 정보를 바탕으로 확인이 필요합니다. 하지만 대부분의 고급 다이어리는 각 연도별로 공휴일을 포함하도록 제작되어 있으니, 내년 공휴일 정보도 포함되어 있을 가능성이 높습니다. 정확한 내용을 확인하려면 가까운 매장이나 고객 서비스에 연락하시는 게 가장 좋을 것 같아요. 도움이 되셨길 바라며, 빠른 답변 부탁드립니다! 😊'}]

In [15]:
result[0]['generated_text'][-1]

{'role': 'assistant',
 'content': '안녕하세요! 다이어리에 내년의 공휴일이 정확히 어떻게 포함되어 있는지 확인해 드리려면 제품 담당자님이 최신 정보를 바탕으로 확인이 필요합니다. 하지만 대부분의 고급 다이어리는 각 연도별로 공휴일을 포함하도록 제작되어 있으니, 내년 공휴일 정보도 포함되어 있을 가능성이 높습니다. 정확한 내용을 확인하려면 가까운 매장이나 고객 서비스에 연락하시는 게 가장 좋을 것 같아요. 도움이 되셨길 바라며, 빠른 답변 부탁드립니다! 😊'}

In [16]:
result[0]['generated_text'][-1]['content']
# ['content'] 키값찾기

'안녕하세요! 다이어리에 내년의 공휴일이 정확히 어떻게 포함되어 있는지 확인해 드리려면 제품 담당자님이 최신 정보를 바탕으로 확인이 필요합니다. 하지만 대부분의 고급 다이어리는 각 연도별로 공휴일을 포함하도록 제작되어 있으니, 내년 공휴일 정보도 포함되어 있을 가능성이 높습니다. 정확한 내용을 확인하려면 가까운 매장이나 고객 서비스에 연락하시는 게 가장 좋을 것 같아요. 도움이 되셨길 바라며, 빠른 답변 부탁드립니다! 😊'

pipeline은 실행할 때마다 다른 답변(텍스트)를 생성함.

pipeline의 파라미터:

* `retune_full_text`: 이전의 대화 기록을 모두 리턴할 여부. 기본값을 True.
* `so_sample`: 샘플링 전략을 사용할 지 여부를 설정. 기본값은 True.
  * `do_sample=True`: 메시지 프롬프트가 같아도 실행할 때마다 생성되는 텍스트가 달라짐.
  * `do_sample=False`
    * 메시지 프롬프트가 같으면 항상 같은 텍스트(답변)가 생성된다.
    * 가장 확률이 높은 토큰들만 선택해서 텍스트를 생성.
* 샘플링 전략
  * temperature(온도)
  * top-k 방식
  * top-p 방식    

In [17]:
result =pipe(messages,
             max_new_tokens=200, # 답변 다양화
             return_full_text=False, # 이전답변 끄기
             do_sample=False) # 항상같은답변으로 나오게하기
print(result)
# result - [ { 'generated_text': '답변...' } ]
# 실행할 때마다 항상 같은 답변.

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '안녕하세요! 다이어리에 내년의 공휴일이 미리 표시되어 있는지에 대해 궁금하시군요. 제품 담당자분께서 가장 정확한 정보를 제공해 드릴 수 있을 것 같아요. 그분께서는 다이어리의 최신 업데이트 내용과 내년 공휴일 정보를 확인하실 수 있으니, 조금 더 자세히 알아보시려면 연락을 취해보시는 건 어떨까요? 친절하게 답변해 드리겠습니다! 😊'}]


# 샘플링 전략 - temperature

In [18]:
result= pipe(messages,
             max_new_tokens=200,
             return_full_text=False,
             temperature=10.0)
print(result)

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': "고객 아드님 맞지예용 ^^. 다이어어나리에 regardsed 국가 정보에서 연말에는 정확치공 국가 정세와 국경 절차나 특별한 날짜의 갱신이 따르우 수 때 많수, 그게 보장 못해요예~ 정확합니다 아시기에 바로 내일부터 내년 기념일도 모두 확정 될 예정이거라도 자세히 미리 알아오니 원하능분엔 저희쪽 기획사으 서비스 안내를 부탁드립니다^◁( '^ω◂)</◕✚"}]


In [19]:
result= pipe(messages,
             max_new_tokens=200,
             return_full_text=False,
             temperature=0.001)
print(result)

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '안녕하세요! 다이어리에 내년의 공휴일이 미리 표시되어 있는지에 대해 궁금하시군요. 제품 담당자분께서 가장 정확한 정보를 제공해 드릴 수 있을 것 같아요. 그분께서는 다이어리의 최신 업데이트 내용과 내년 공휴일 정보를 확인하실 수 있으니, 조금 더 자세히 알아보시려면 연락을 취해보시는 건 어떨까요? 친절하게 답변해 드리겠습니다! 😊'}]


temperature(온도)를 1보다 큰 값을 사용하면 문장을 생성할 때 선택되는 토큰들이 다양해 지기 때문에 갑변이 무작위짐.

temperature를 1보다 작은 값을 사용하면 높은 확률을 가진 토큰들이 선택될 가능성이 더 커짐. 생성되는 답변이 더 일관적이게 됨.

In [20]:
# 동전 던지기
probs = [0.5, 0.5] # 앞면 확률, 뒷면 확률

np.random.multinomial(n=100,pvals=probs) # 동전 던지기 100번 실험

array([51, 49])

In [21]:
# 주사위 던지기
probs =[1/6]*6
np.random.multinomial(n=600, pvals=probs)

array([105,  90,  93, 103, 105, 104])

logit(로짓): softmax 함수의 아규먼트. LLM에서는 어휘 사전에 포함된 각 토큰에 대한 점수.

In [22]:
logits = [1,2,3,4,10] # 5개의 토큰의 점수
probs = scipy.special.softmax(logits)
print(probs)

[1.22936559e-04 3.34176214e-04 9.08385131e-04 2.46924679e-03
 9.96165255e-01]


In [23]:
np.sum(probs)

np.float64(1.0)

In [24]:
np.random.multinomial(n=200, pvals=probs)

array([  0,   0,   0,   0, 200])

In [25]:
logits= np.array([1,2,3,4,100])
probs=scipy.special.softmax(logits)
print(probs)

[1.01122149e-43 2.74878501e-43 7.47197234e-43 2.03109266e-42
 1.00000000e+00]


In [26]:
np.random.multinomial(n=200, pvals=probs)

array([  0,   0,   0,   0, 200])

In [27]:
probs = scipy.special.softmax(logits / 10) # 리스트는 + * 만가능
                                           # 배열은 나누기도 가능
print(probs)
np.random.multinomial(n=200,pvals=probs)

[5.01629119e-05 5.54385914e-05 6.12691190e-05 6.77128484e-05
 9.99765417e-01]


array([  0,   0,   0,   0, 200])

In [28]:
probs = scipy.special.softmax(logits / 100) # 리스트는 + * 만가능
                                           # 배열은 나누기도 가능
print(probs)
np.random.multinomial(n=200,pvals=probs)

[0.14810557 0.14959406 0.1510975  0.15261606 0.39858682]


array([27, 30, 33, 29, 81])

In [29]:
probs = scipy.special.softmax(logits / 0.1) # 리스트는 + * 만가능
                                           # 배열은 나누기도 가능
print(probs)
np.random.multinomial(n=200,pvals=probs)

[0. 0. 0. 0. 1.]


array([  0,   0,   0,   0, 200])

* logit 값들을 1보다 큰 수로 나눈 후 softmax 함수로 확률을 계산하면, logit 값이 작은 토큰들의 확률이 커지는효과가 생긴다.
  * 토큰을 선택하는 다양성이 커진다.
  * 생성되는 텍스트가 다양해짐.
* logit 값들을 1보다 작은수로 나눈후에 softmax로 확률을 계산하면, logit값이 큰 토큰들의 확률을 더 크게 만드는 효과가 생김.
  * 토큰을 선택하는 다양성이 작아진다.
  * 거의 비슷한 텍스트들이 생성된다.
* LLM에서 온도(temoerature)는 logit 값들을 나눠주는 수.  

# top-k 샘플링

모델이 계산한 logit(점수) 값들을 정렬해서 최상위 k개의 토큰들 중에서 선택하는 방법.

k값이 클 수록 더 다양한 텍스트들이 생성될 수 있음.

In [31]:
result =pipe(messages,
             max_new_tokens=200,
             return_full_text=False,
             temperature=100.5,
             top_k=100)
print(result)

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '네버바디 정확행보이신거로 볼게요  제가 시스템 자체니 때문필릴하여 정답 바로 전달 Cannot assist the solution straight moment need 팀 담당자까지 그 외 많가지 경우사정 필요있다수분같은이정확부분 미리 고민하긴 힘든데 꼭 현재 위치상태 보시시고 다이어리 옆엔 제품 라벨를도 확인시라보실기관 관계자있드시도확인만 확실이게하면어�dain다 이해되도록 많게하는데조금도움 주더익습니다 어떻게 보시실? 함께 시간 잘 지내셔서 만족했기에 말씀 전하오예.. 🙂❤ning your consultation take warmth needs하셨져라 응원요합당해질까지! 알엔게 걱정마라 시간들 준비 꼭 다시한번봐볼개론요 💺 필요궁금하고 불처 이해 확인히고있다고 도움다시 줄개있으면 말들어놓네 이렇게! 필요것아닌 도움 드리죠 기다리라 우리 연결 또 연결부러 싶게요~ 안녕하라 요 기간 후 모두 안전행운하고 새로운기간유'}]


# top-p 샘플링

모델이 출력한 logit 값으로 계산한 확률의 크기 순으로 정렬했을 때 누적 확률 p까지의 토큰을 선택하는 방법.

top_p(누적 확률) 값이 클 수록 다양한 텍스트, 작을 수록 일관된 텍스트들이 생성됨.

누적 확률 p가 동일하더라도 선택될 수 있는 토큰의 개수가 달라질 수 있음.

top-p 샘플링은 다양한 확률 분포에 유연하게 대처할 수 있음.

top-k 샘플링은 선택하는 토큰들의 개수를 고정하기 때문에, 높은 확률을 가진 토큰이 선택에서 제외될 가능성이 있음.

In [32]:
result=pipe(messages,
            max_new_tokens=200,
            return_full_text=False,
            temperature=1.5,
            top_p=0.9)
print(result)

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'top_p', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '그럼요, 맞답니다! 각 연도의 다이어리에는 해당 년도의 공휴일이 미리 잘 표기되어 있거든요. 자세히 보고 싶으시다면 가까운 매장을 방문하셔서 직접 확인하시는 게 가장 정확할 거예요. 제품 설명이나 카탈로그에서도 몇 가지 정보가 제공될 수 있으니 그 내용도 참고하시기 바랍니다! 궁금하신 점이 더 있으시다면 언제든지 편하게 물어보세요.'}]


In [33]:
result=pipe(messages,
            max_new_tokens=200,
            return_full_text=False,
            temperature=1.5,
            top_p=0.3)
print(result)

Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '안녕하세요! 다이어리에 내년의 공휴일이 미리 표시되어 있는지에 대해 궁금하시군요. 현재로선 정확한 답변을 드리기 어렵습니다. 제품 담당자분께서 가장 최신의 정보와 함께 정확한 답변을 주시려고 노력하고 계시답니다. 조금만 기다려 주시면 바로 확인해 드릴 수 있을 것 같아요. 궁금한 점이 더 있으시면 언제든지 알려주세요!'}]
